version: "3"
services:
  front-end:
    container_name: frontend
    # image: oshabz/marble-arch-frontend:1.0
    build:
      context: ./frontend
      args:
        - REACT_APP_DEV_BASE_URL=http://backend:7500/api/
    stdin_open: true
    tty: true
    ports:
      - 5173:80
    networks:
      - oshabz-marketplace
    environment:
      - REACT_APP_DEV_BASE_URL=http://backend:5173/api/
    depends_on:
      - backend
  backend:
    container_name: backend
    image: backend
    build: ./backend
    ports:
      - 8800:8800
    networks:
      - oshabz-marketplace
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - oshabz-marketplace
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - oshabz-marketplace
    depends_on:
      - mongo
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
networks:
  oshabz-marketplace: {}

volumes:
  mongodb:
    driver: local
  mongodb_config:
